
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-kube-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: argocd-kube
  template:
    metadata:
      labels:
        run: argocd-kube
    spec:
      - image: 160885288882.dkr.ecr.ap-northeast-2.amazonaws.com/web-site:8790911
      - image: 
        name: argocd-kube
